2024-12-02 18:07:52,867 - app - ERROR - Internal Server Error: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
2024-12-02 18:08:29,507 - app - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "/home/paula-luna-navarro/uvlhub/venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/paula-luna-navarro/uvlhub/venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/paula-luna-navarro/uvlhub/venv/lib/python3.12/site-packages/flask_restful/__init__.py", line 298, in error_router
    return original_handler(e)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/paula-luna-navarro/uvlhub/venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/paula-luna-navarro/uvlhub/venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/paula-luna-navarro/uvlhub/app/modules/public/routes.py", line 30, in index
    return render_template(
           ^^^^^^^^^^^^^^^^
  File "/home/paula-luna-navarro/uvlhub/venv/lib/python3.12/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/paula-luna-navarro/uvlhub/venv/lib/python3.12/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/paula-luna-navarro/uvlhub/venv/lib/python3.12/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/home/paula-luna-navarro/uvlhub/venv/lib/python3.12/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/paula-luna-navarro/uvlhub/app/modules/public/templates/public/index.html", line 1, in top-level template code
    {% extends "base_template.html" %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/paula-luna-navarro/uvlhub/app/templates/base_template.html", line 75, in top-level template code
    <a class="sidebar-link" href="{{ url_for('ia_bp.ia') }}">
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/paula-luna-navarro/uvlhub/venv/lib/python3.12/site-packages/flask/app.py", line 1084, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/paula-luna-navarro/uvlhub/venv/lib/python3.12/site-packages/flask/app.py", line 1073, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/paula-luna-navarro/uvlhub/venv/lib/python3.12/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'ia_bp.ia'. Did you mean 'auth.login' instead?
2024-12-02 18:08:29,511 - app - ERROR - Internal Server Error: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
2024-12-02 18:08:31,265 - app - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "/home/paula-luna-navarro/uvlhub/venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/paula-luna-navarro/uvlhub/venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/paula-luna-navarro/uvlhub/venv/lib/python3.12/site-packages/flask_restful/__init__.py", line 298, in error_router
    return original_handler(e)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/paula-luna-navarro/uvlhub/venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/paula-luna-navarro/uvlhub/venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/paula-luna-navarro/uvlhub/app/modules/public/routes.py", line 30, in index
    return render_template(
           ^^^^^^^^^^^^^^^^
  File "/home/paula-luna-navarro/uvlhub/venv/lib/python3.12/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/paula-luna-navarro/uvlhub/venv/lib/python3.12/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/paula-luna-navarro/uvlhub/venv/lib/python3.12/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/home/paula-luna-navarro/uvlhub/venv/lib/python3.12/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/paula-luna-navarro/uvlhub/app/modules/public/templates/public/index.html", line 1, in top-level template code
    {% extends "base_template.html" %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/paula-luna-navarro/uvlhub/app/templates/base_template.html", line 75, in top-level template code
    <a class="sidebar-link" href="{{ url_for('ia_bp.ia') }}">
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/paula-luna-navarro/uvlhub/venv/lib/python3.12/site-packages/flask/app.py", line 1084, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/paula-luna-navarro/uvlhub/venv/lib/python3.12/site-packages/flask/app.py", line 1073, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/paula-luna-navarro/uvlhub/venv/lib/python3.12/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'ia_bp.ia'. Did you mean 'auth.login' instead?
2024-12-02 18:08:31,269 - app - ERROR - Internal Server Error: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
